# Generated by Django 4.2 on 2023-05-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_problem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(default='Easy', max_length=6),
            preserve_default=False,
        ),
    ]
